parserOptions:
  ecmaVersion: 2015
  sourceType: 'module'

env:
  es6: true
  browser: true
  commonjs: true
  node: true

rules:
  object-curly-spacing:
    - error
    - "always"

extends: 'htmlacademy/es6'
